### ISSUE TITLE
Data structure for the UI

### ISSUE THREAD

**Issue by ayushi-roy** [18F/cms-carts-seds#144]
And lay them out on each section. This involves adding the UI structure to the backend JSON API.

For the production build, each component will ingest and display data from the JSON API, generated by postgres+django backend. This build is separate from the prototype, where data is hard-coded in react pages. To make the components dynamic, we'll add the UI structure data to each question in the backend JSON. When the react application calls the API, it will know exactly which component to display for each question.

**Goals:**
1. Get data from the JSON API
2. Display data as components in each section
3. Send a response with updated/saved data

AC:
1. 

Related to #155, #192, #33

**Comment by cannandev** [comment]
Working on mock JSON to gather that info. See progress here: https://github.com/18F/cms-carts-seds/tree/experiment/build-ui-json

**Comment by cannandev** [comment]
Per latest discussion with Tadhg, need the following
- [ ] add section parts, year and state
- [ ] remove UUID

On the react side:
- [ ] separate API call to previous year (structure is `/api/reports/2020/ny/section/1/`)
- [ ] create react routes for each section dynamically
- [ ] get test page running displaying sections with their components

**Comment by TaraWilliamsPGH** [comment]
@cannandev Can you please groom this ticket for what is left post-Entemann's sprint related work.
