### ISSUE TITLE
Set up Redux to read postgres JSON and send output to front end

### ISSUE THREAD

**Issue by jgillis1** [18F/cms-carts-seds#316]
As a developer, I need to be able to use Redux to read/write data from/to the postgres database and display the data appropriately on the front end. Utilize Axios to make API calls.

AC:

- [x] Frontend is able to read data from postgres database (#391, #401)

- [x] Frontend is able to write data to postgres database (#412)

- [ ] One fully functioning section by end of sprint

- [x] Use axios (see #391 )

- [x] Use JsonPath to extract values. (#401)

**Comment by mgwalker** [comment]
I'll work on writing answers back to the API this afternoon or in the morning. It'll key off the `QUESTION_ANSWERED` action from #401, so if everything continues to use that, we should be good to go.
