### ISSUE TITLE
Road to production 🛣️

### ISSUE THREAD

**Issue by cannandev** [18F/cms-carts-seds#351]
Acceptance criteria from Prototype to MVP. 
**Pen test 9/28**

- [ ] Working User Authentication #392 
- [ ] User Permissions #462 
- [ ] All sections can be submitted #416 
- [ ] Save to database #475 #256 Working autosave feature (needs an endpoint, https, blocked by user auth + permissions)
- [ ] Login + Home + nav pages
- [x] FMAP rate support #522 
- [ ] Pen Test requirements #387 
- [ ] Deploy to test environments
- [ ] Testing / validation / UAT #179 #260

## Environment
- [x] Working CI on dev url - [mdctcartsdev.cms.gov](mdctcartsdev.cms.gov)
- [ ] Request prod url - [mdctcarts.cms.gov](mdctcarts.cms.gov) (requested but not returned)
- [ ] Jest-enzyme tests

## Users/Views
- [ ] Okta login/logout
- [ ] users and user roles
- [ ] Reports for all 50 states (#367, #393)

## Pages/Views
- [ ] Form Sections 0-7 [see Components List](https://docs.google.com/spreadsheets/d/1mCzbOGkNnx6i_e05cl-GxzzQKEqJOpFT4XAtlLjpqPs/edit#gid=573545140)
- [ ] Access denied page (#375)
- [x] View Only/Download (Entire Document)
- [x] Print View (Section - no previous year)
- [ ] Word doc version?

### Concerns
- [ ] How will central office users access any pre-2020 data once the new application is launched?

### Moved to v2?
- [ ] Import from last year
- [ ] Previous year tabs
- [ ] Federal user view
- [ ] Review (Non-interactive) view
- [ ] Temporary Share URL - Data Centralizer view, Data SME view (#333)
- [ ] Uncertify view? What happens when the user clicks 'Uncertify' on homepage?
- [ ] Admin user view?
