### ISSUE TITLE
Populate data for MVP launch (epic)

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#636]
As a state user, I want to have key data points saved in CARTS so that I am able to complete my form.

- [ ] #720 - State user accounts created
- [ ] #613 - Basic information section has prefilled data (state, program name, program type)
- [x] #639 - Section 2, part 1 - SEDS data is filled
  - Related issues completed so far: 
    - #193 (map SEDS data)
    - #189 (Data migration plan)
- [x] #477 - Section 2, part 2 - ACS data is prefilled
- [x] #522 - Section 5 - FMAP rate for 2020 is prefilled

**Comment by TaraWilliamsPGH** [comment]
@StephanieCoppel - can this be closed? we already have epics for these things, correct?

**Comment by StephanieCoppel** [comment]
@TaraWilliamsPGH the state user info hasn't been fully populated... to my knowledge? but i could be wrong?

**Comment by StephanieCoppel** [comment]
all stories covered elsewhere - closing this
