### ISSUE TITLE
Run JSON files through prettier and autogenerate fixtures

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/cms-carts-seds#670]
The JSON files are large enough, and have enough people working through them, that tracking down changes/differences in them would benefit from removing whitespace as a consideration. ~In addition, the fixtures files are all currently on one line (because Django doesn't really care how they're formatted) but there have been and will be times we're trying to find differences in those as well, so they should be passed through a formatter to make them more legible as well.~
We should not deal with the fixtures files at all and should autogenerate them instead.

`prettier` is the standard JS tool for this.

AC:
- [x] `prettier` is part of the project.
- [x] ~~`generate_fixtures.py` either calls `prettier` itself or is part of a pipeline that does so (in all environments).~~ Made obsolete by #681.
- [x] ~~This will be clearly visible when the fixtures files are no longer a single really long line.~~ Resolved this by deleting the fixtures files and autogenerating them instead; see #681.
- [x] Fixtures for generic sections are autogenerated. Done in #681.
- [ ] ~~State-specific files no longer have to be created as separate JSON files but are generated from generic sections and modified to include Section 0 answers. Mostly done in #683, but the fixture-loading problem addressed by https://github.com/18F/cms-carts-seds/pull/692 makes me unwilling to mark this as done.~~
- [x] (Stretch goal): git hook that runs prettier on the JSON files in `/docs/section-schemas` when checking them in. Done in #684

**Comment by tadhg-ohiggins** [comment]
@StephanieCoppel @TaraWilliamsPGH @cjhskippy ☝️

**Comment by TaraWilliamsPGH** [comment]
@tadhg-ohiggins will this impact the current release? Could we move this to Layer?

**Comment by tadhg-ohiggins** [comment]
Making it easier to find errors in the JSON should make hitting the current release more likely. This is a minor lift and should not meaningfully alter my workload, and is likely to make any JSON review (which is definitely going to be necessary) faster.

**Comment by tadhg-ohiggins** [comment]
Will mark as done as soon as #684 is merged.

**Comment by cjhskippy** [comment]
Moved AC#5 to #354 as it's more closely related to our need for production-ready deployment than fixture formatting.
