### ISSUE TITLE
Document Status - Certified and Submitted

### ISSUE THREAD

**Issue by StephanieCoppel** [18F/cms-carts-seds#741]
This epic is intended to capture all of the work that leads a report into the Certified and Submitted status and then on to the next stages.
- This process is always kicked off by state users certifying their report. (#385)
- Once a document has been certified:
  - [ ] state user, CHIP Project Officer and Business Owners can view the report, but cannot edit it (#757)
  - [ ] CHIP Project Officers can uncertify the report (#758) 
     - Includes triggering a notification to state report users.
  - [ ] CHIP Project Officers can accept the report (#759)
     - Includes triggering a notification to state report users.

**WORKFLOW MURAL:** https://app.mural.co/t/upmc4555/m/upmc4555/1601924190266/917889a4d9489374a4f5fd0a043f9ed41f27bb8c

**Comment by TaraWilliamsPGH** [comment]
Closed in favor of Document Status and Workflow Epic
